### ISSUE TITLE
SEO: unclear on implementing or data-binding to <head> elements... (<title> , <meta>, <etc>...)

### ISSUE THREAD

**Issue by oneezy** [Polymer/shop#22] opened 2016-05-19 06:33 UTC
It's unclear, or I haven't found the documentation for implementing SEO (in particular, data-binding to elements inside the `<head></head>` element. What is the proper way or best practice to follow with the new and improved `<app-route>` element?

**Example:**
        
        
        <title>[[shopTitle]]</title>
        
        
        <meta name="author" itemprop="name" content="[[shopTitle]]">
        <meta name="description" itemprop="description" content="[[shopDescription]]">
        <link rel="canonical" href="[[shopLink]]">
        
        
        <meta name="twitter:card" content="[[shopSummary]]">
        <meta name="twitter:site" content="[[shopAuthor]]">
        <meta name="twitter:creator" content="[[shopAuthor]]">
        <meta name="twitter:title" content="[[shopTitle]]">
        <meta name="twitter:url" content="[[shopLink]]">
        <meta name="twitter:description" content="[[shopDescription]]">
        <meta name="twitter:image:src" content="[[shopImage]]">
        
        
        <meta property="og:site_name" content="[[shopDescription]]">
        <meta property="og:url" content="[[shopLink]]">
        <meta property="og:type" content="shopType">
        <meta property="og:title" content="[[shopTitle]]">
        <meta property="og:description" content="[[shopDescription]]">
        <meta property="og:image" content="[[shopImage]]">
        <meta property="fb:app_id" content="[[shopID]]">
        <meta property="fb:admins" content="[[shopAdmins]]">
        
        
        <meta itemprop="image" content="[[shopImage]]">

**Comment by frankiefu** [comment] 2016-05-20 17:38
Duplicate of https://github.com/Polymer/polymer/issues/3249

**Closed by frankiefu** 2016-05-20 17:38 UTC
Labels: duplicate
