### ISSUE TITLE
Detail page doesn't load at times - 404 Message

### ISSUE THREAD

**Issue by jeff-hernandez** [Polymer/shop#100] opened 2016-11-17 22:38 UTC
At random times, the detail page of the product doesn't load outputting message 404 page not found.

**Comment by frankiefu** [comment] 2016-12-21 19:25
I can't reproduce the issue in the [live demo](https://shop.polymer-project.org/) or running shop locally.  Can you give us more info on how to reproduce the issue?

**Comment by mchyb** [comment] 2017-01-22 12:49
Whenever I open any product detail page and then switch to another category page to open another product page, I get the 404 view. I tested it with the version downloaded directly from github repo and with the one that is downloaded by Polymer CLI.

**Comment by frankiefu** [comment] 2017-01-24 18:12
@TimvdLippe This seems to be a bug in the "Add 404 fallback" changes you did.  Seems like it's sending `show-invalid-url-warning` event when it shouldn't.  Do you mind taking a look?

**Comment by mchyb** [comment] 2017-01-24 18:27
It seems like, after opening an item detail page, the routeData.item property is being updated before routeData.category causing the _computeItem function to run too early.

**Comment by TimvdLippe** [comment] 2017-01-24 22:21
Hm yes it appears to be an observer issue. I will take a look tomorrow!

**Comment by frankiefu** [comment] 2017-01-31 01:35
Should be fixed now.

**Closed by frankiefu** 2017-01-31 01:35 UTC
Labels: bug
