### ISSUE TITLE
app-route and selected tab – reload the whole app?

### ISSUE THREAD

**Issue by ymaz** [Polymer/shop#51] opened 2016-06-23 20:08 UTC
Hi guys, just looking into your shop-app to discover more about Polymer and <app-route>, thank you for sharing, it's a really very good point to start.

So, I've have a question: is that okay, when you hit again on already selected tab (desktop view), and it's reload (re-init) the whole application from scratch? Is that issue inside `<app-route>`? Or I should handle this case by myself and disable, for example, current active tab, to avoid reload the application.

Actually, i'm assuming that application shouldn't be reloaded when the same url (path) is already present, when you click on link with equal url.

Many thanks,

**Comment by keanulee** [comment] 2016-06-24 17:26
@ymaz When you click on a link to the page you're already on, the whole app _should not_ reload. This behavior should be provided by `app-route` (specifically, its dependency `iron-location` installs a global click handler that `preventDefault`s on same origin links - see https://github.com/PolymerElements/iron-location/blob/master/iron-location.html#L236).

I don't see this reloading behavior on Chrome, Firefox and Safari. Is this something you're seeing?

**Comment by ymaz** [comment] 2016-06-24 18:45
@keanulee thanks for quick reply!

I've spotted that issue, on my localhost:8080/, when running the shop app in Firefox.

I see, that iron-location is preventing that click, but somehow i can reproduce that, please check below:

![gif polymer-shop-01](https://cloud.githubusercontent.com/assets/1445929/16347305/fdada0a0-3a19-11e6-9aa4-d55ac57ba439.gif)

So, I'm clicking between the tabs, everything works as expected, but when i hit the same selected tab, app is reloading...

**Comment by keanulee** [comment] 2016-06-24 19:00
Still can't reproduce - are you using the latest version of Firefox (47)?

**Comment by ymaz** [comment] 2016-06-24 20:03
Yeah, strange, more info from my side:
`  "name": "iron-location",
  "version": "0.8.4"`

`  "name": "app-route",
  "version": "0.9.2"`

`  "name": "polymer",
  "version": "1.5.0"`

**Comment by keanulee** [comment] 2016-06-24 21:14
Ah, I didn't have the latest versions of `iron-location`. I was able to reproduce and filed a bug (referenced above). Thanks @ymaz !

Closing since this issue is with iron-location.

**Closed by keanulee** 2016-06-24 21:14 UTC

**Comment by ymaz** [comment] 2016-06-24 22:02
@keanulee, many thanks! Looking forward to get fix soon:)
